# -*- coding: utf-8 -*-
"""Soal A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XtSj0cdVpttcqCBdNo7BbM572BsjlJ3u

# **Jawaban Nomor 3**
"""

# Import packages 
import pandas as pd
import datetime
import dateutil
  
# Mendefinisikan data dictionary  
data = {'ID': [1, 2, 3], 
        'FullName': ['Stan Smith', 'Nikola Griffin', 'Ruby Moore'], 
        'Gender': ['Male', 'Male', 'Female'],
        'DateOfBirth':[date(1960,2,10), date(1999,12,20), date(2002,3,3)]} 

# Konversi dictionary ke DataFrame 
df = pd.DataFrame(data)

# FUNGSI MENENTUKAN USIA
def birthday(row):
    # Tanggal hari ini
    now = datetime.datetime.utcnow()
    now = now.date()

    # Mencari perbedaan tahun dari tanggal saat ini dan tanggal lahir
    age = dateutil.relativedelta.relativedelta(now, row['DateOfBirth'])
    age = age.years

    return age

# Memasukkan kolom usia ke dataframe
# kolom ini merupakan kolom sementara
df['Age'] = df.apply (lambda row: birthday(row), axis=1)

# FUNGSI MENENTUKAN GOLONGAN USIA
def age_group (row):
  if row['Age'] >= 60 :
    return 'Senior Adult'
  if row['Age'] > 18 and row['Age'] < 60  :
    return 'Adult'
  if row['Age'] <= 18 and row['Age'] > 12  :
    return 'Teen'

# Menambah kolom AgeGroup 
df['AgeGroup'] = df.apply (lambda row: age_group(row), axis=1)

# menghapus kolom Age (yang bersifat sementara)
del df['Age']

# FINAL OUTPUT
df